# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

use_frameworks!

target 'VeracitySample' do
#  pod 'VeracitySDK', :path => '../../ios-sdks-build/Projects/VeracitySDK/'
  pod 'VeracitySDK', :git => 'https://github.com/oneprove/ios-public-sdk.git'
  pod "ReachabilitySwift"
  pod 'Alamofire'
end

target 'DemoClip' do
  source 'https://github.com/CocoaPods/Specs.git'
  source 'https://github.com/oneprove/specs-oneprove.git'

  pod 'BlurDetector'
end
